# Generated by Django 4.1.6 on 2023-03-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrc_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(max_length=255, null=True, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='account',
            name='county',
            field=models.CharField(choices=[('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Donegal', 'Donegal'), ('Dublin', 'Dublin'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], max_length=20, null=True, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='account',
            name='eircode',
            field=models.CharField(max_length=7, null=True, verbose_name='eircode'),
        ),
        migrations.AddField(
            model_name='account',
            name='forename',
            field=models.CharField(max_length=255, null=True, verbose_name='forename'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=255, null=True, verbose_name='surname'),
        ),
    ]
