# Generated by Django 4.1.6 on 2023-03-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otrc_accounts', '0002_account_address1_account_address2_account_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
