# Generated by Django 4.1.6 on 2023-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrc_accounts', '0003_remove_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paypalJWT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
