# Generated by Django 4.1.6 on 2023-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrc_accounts', '0004_alter_account_paypaljwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='eircode',
            field=models.CharField(max_length=12, null=True, verbose_name='eircode'),
        ),
    ]
